// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuNxH7X0VvpnL-ot0T0SB1f9_y_naI0Os',
    appId: '1:893886916778:web:4b5746c10b2fe84cefc8d3',
    messagingSenderId: '893886916778',
    projectId: 'dstrct-server',
    authDomain: 'dstrct-server.firebaseapp.com',
    databaseURL: 'https://dstrct-server-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dstrct-server.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNgMXy_pSHo2--ycubnlLLVSEC7LFa3Q4',
    appId: '1:893886916778:android:2d05b6557c5a6f95efc8d3',
    messagingSenderId: '893886916778',
    projectId: 'dstrct-server',
    databaseURL: 'https://dstrct-server-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dstrct-server.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnnpROpGfusktFAZ9XM9JL_F_RXmLvzws',
    appId: '1:893886916778:ios:adeb8f62e4e518f1efc8d3',
    messagingSenderId: '893886916778',
    projectId: 'dstrct-server',
    databaseURL: 'https://dstrct-server-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dstrct-server.appspot.com',
    iosClientId: '893886916778-h16lq8fjvt7svsnvi1331e0bg9514rqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnnpROpGfusktFAZ9XM9JL_F_RXmLvzws',
    appId: '1:893886916778:ios:beb341f4a3286589efc8d3',
    messagingSenderId: '893886916778',
    projectId: 'dstrct-server',
    databaseURL: 'https://dstrct-server-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dstrct-server.appspot.com',
    iosClientId: '893886916778-jei5q1cm3hb2nmcq63os5k9g1je148fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
